# Generated by Django 2.0.4 on 2018-04-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classtime',
            name='day',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classtime',
            name='section',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='credit',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='token',
            field=models.DecimalField(decimal_places=0, max_digits=8, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name_eng',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
