# Generated by Django 2.0.4 on 2018-04-30 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querysys', '0002_auto_20180430_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name_zh', models.CharField(max_length=50)),
                ('name_eng', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='college_program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='querysys.CollegeProgram'),
        ),
    ]
