# Generated by Django 2.0.4 on 2018-05-06 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysys', '0004_auto_20180430_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collegeprogram',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='department',
            name='name_eng',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='name_eng',
        ),
    ]
