# Generated by Django 2.0.4 on 2018-06-24 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('querysys', '0007_auto_20180624_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='token',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
